apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    app.kubernetes.io/name: games
    app.kubernetes.io/instance: games
    app.kubernetes.io/version: '20201212'
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
  annotations:
    downscaler/uptime: 'Mon-Fri 06:32-24:00 UTC,Tue-Sat 00:00-01:00 UTC'