apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: games
  labels:
    app.kubernetes.io/name: compute-resources
    app.kubernetes.io/instance: compute-resources
    app.kubernetes.io/version: '20201212'
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
spec:
  hard:
    requests.cpu: '4'
    requests.memory: 8Gi
    limits.cpu: '4'
    limits.memory: 8Gi
    requests.nvidia.com/gpu: '4'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: games
  labels:
    app.kubernetes.io/name: object-counts
    app.kubernetes.io/instance: object-counts
    app.kubernetes.io/version: '20201212'
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
spec:
  hard:
    configmaps: '40'
    secrets: '40'
    persistentvolumeclaims: '8'
    pods: '40'
    services: '20'
    services.loadbalancers: '1'
